version: "3"
services:
  api-server:
    # image: api-server
    build: ./backend
    ports:
      - "9080:9080"
    networks:
      - mern-app
  react-app:
    # image: react-app
    build:
      context: ./chirp
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "80:80"
    networks:
      - mern-app
    # depends_on:
    #   - api-server
  # nginx-media:
  #   # image: media-server
  #   build: ./nginx-media
  #   ports:
  #     - "1935:1935"
  #     # - "8000:8000"
  #   networks:
  #     - mern-app
  media-server:
    build: ./mediaserver
    # image: media-server
    ports:
      - "1935:1935"
      - "8000:8000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
# volumes:
#   mongo-data:
#     driver: local
